Logging: 
  IncludeScopes: false
  LogLevel: 
    Default: Debug
    System: Debug
    Microsoft: Debug
eureka:
  client: 
    serviceUrl: http://localhost:8761/eureka/
    validate_certificates: false
